[package]
name = "game-kb-driver"
version = "0.1.24"
authors = ["Anicka Burova <anicka.burova@gmail.com>"]

[dependencies]
libusb = "*"
libxdo = "*"
yaml-rust = "*"
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"


